@echo off
chcp 1251 >nul
setlocal EnableDelayedExpansion

title LCP STARTER C++ Compiler v1.0

set "PD=%~dp0"
set "NASM=%PD%NASM\nasm.exe"
set "GOLINK=%PD%GoLink\GoLink.exe"
set "ERRFILE=%PD%err.txt"

echo ==========================================
echo    LCP STARTER C++ - COMPILER v1.0
echo    (c) LCP CORPORATION
echo    Russian C++ .lcplus to .exe
echo ==========================================
echo.

if not exist "%NASM%" (
    echo [ERROR] NASM not found: %NASM%
    echo [ERROR] NASM not found: %NASM% > "%ERRFILE%"
    pause
    exit /b 1
)

if not exist "%GOLINK%" (
    echo [ERROR] GoLink not found: %GOLINK%
    echo [ERROR] GoLink not found: %GOLINK% > "%ERRFILE%"
    pause
    exit /b 1
)

if not exist "%PD%LCP_STARTER.ASM" (
    echo [ERROR] LCP_STARTER.ASM not found
    echo [ERROR] LCP_STARTER.ASM not found > "%ERRFILE%"
    pause
    exit /b 1
)

if not exist "%PD%LCP_STARTER_C.ASM" (
    echo [ERROR] LCP_STARTER_C.ASM not found
    echo [ERROR] LCP_STARTER_C.ASM not found > "%ERRFILE%"
    pause
    exit /b 1
)

set "INFILE=%~1"
if "%INFILE%"=="" for %%f in (*.lcplus) do set "INFILE=%%f"
if "%INFILE%"=="" (
    echo [ERROR] No .lcplus file found
    echo [ERROR] No .lcplus file found > "%ERRFILE%"
    pause
    exit /b 1
)

if not exist "%INFILE%" (
    echo [ERROR] File not found: %INFILE%
    echo [ERROR] File not found: %INFILE% > "%ERRFILE%"
    pause
    exit /b 1
)

for %%f in ("%INFILE%") do set "NAME=%%~nf"
for %%f in ("%INFILE%") do set "EXT=%%~xf"

if /i not "%EXT%"==".lcplus" (
    echo [ERROR] Only .lcplus files supported
    echo [ERROR] Wrong extension: %EXT% > "%ERRFILE%"
    pause
    exit /b 1
)

set "PLATFORM=%~2"
if "%PLATFORM%"=="" (
    echo.
    echo Select platform:
    echo   1 = x86 (32-bit)
    echo   2 = x64 (64-bit)
    echo.
    set /p "CH=Choice: "
    if "!CH!"=="1" set "PLATFORM=x86"
    if "!CH!"=="2" set "PLATFORM=x64"
    if "!PLATFORM!"=="" set "PLATFORM=x86"
)

set "EXE=%NAME%.exe"
set "ASM=%NAME%.asm"
set "OBJ=%NAME%.obj"

if "!PLATFORM!"=="x86" (
    set "NFMT=win32"
    set "ENTRY=_main"
)
if "!PLATFORM!"=="x64" (
    set "NFMT=win64"
    set "ENTRY=main"
)

echo.
echo Source: %INFILE%
echo Platform: %PLATFORM%
echo Output: %EXE%
echo.

echo [1/3] Translating .lcplus...

set "TEMP1=%PD%_temp1_.tmp"
set "TEMP2=%PD%_temp2_.tmp"
set "TEMP3=%PD%_temp3_.tmp"

echo ; Generated by LCP STARTER C++ v1.0 > "%ASM%"
echo ; Source: %INFILE% >> "%ASM%"
echo. >> "%ASM%"

set "INCL1=%%include"
echo !INCL1! "LCP_STARTER.ASM" >> "%ASM%"
echo !INCL1! "LCP_STARTER_C.ASM" >> "%ASM%"
echo. >> "%ASM%"
echo ÈÌÏÎÐÒ >> "%ASM%"
echo. >> "%ASM%"
echo ÑÅÊÖÈß_ÄÀÍÍÛÕ >> "%ASM%"
echo. >> "%ASM%"

for /f "usebackq tokens=* delims=" %%a in ("%INFILE%") do (
    set "L=%%a"
    set "W1=!L:~0,17!"
    if "!W1!"=="ñòðîêà_îïðåäåëèòü" (
        set "REST=!L:~18!"
        for /f "tokens=1,* delims==" %%b in ("!REST!") do (
            set "V=%%b"
            set "S=%%c"
            set "V=!V: =!"
            set "S=!S:"=!"
            echo !V!: db "!S!", 0 >> "%ASM%"
            echo !V!_len equ $ - !V! - 1 >> "%ASM%"
        )
    )
)

echo. >> "%ASM%"
echo ÑÅÊÖÈß_BSS >> "%ASM%"
echo _keybuf: resb 1 >> "%ASM%"
echo. >> "%ASM%"
echo ÑÅÊÖÈß_ÊÎÄÀ >> "%ASM%"
echo. >> "%ASM%"
echo ÃËÀÂÍÀß >> "%ASM%"
echo. >> "%ASM%"

for /f "usebackq tokens=* delims=" %%a in ("%INFILE%") do (
    set "L=%%a"
    set "W1=!L:~0,17!"
    if not "!W1!"=="ñòðîêà_îïðåäåëèòü" (
        if "!L!"=="" (
            echo. >> "%ASM%"
        ) else (
            set "O=!L!"
            set "O=!O:íàïå÷àòàòü =ÍÀÏÅ×ÀÒÀÒÜ !"
            set "O=!O:çàâåðøèòü=ÇÀÂÅÐØÈÒÜ!"
            set "O=!O:çàâåðøèòü_áåç_îæèäàíèÿ=ÇÀÂÅÐØÈÒÜ_ÁÅÇ_ÎÆÈÄÀÍÈß!"
            echo !O! >> "%ASM%"
        )
    )
)

echo. >> "%ASM%"
echo ÊÎÍÅÖ_ÃËÀÂÍÎÉ >> "%ASM%"

echo [2/3] Assembling...
"%NASM%" -f %NFMT% "%ASM%" -o "%OBJ%" -i "%PD%" 2>_nasm_err.txt
if errorlevel 1 (
    echo [ERROR] NASM failed
    echo NASM Error: > "%ERRFILE%"
    type _nasm_err.txt >> "%ERRFILE%"
    echo. >> "%ERRFILE%"
    echo Generated ASM file: >> "%ERRFILE%"
    type "%ASM%" >> "%ERRFILE%"
    echo.
    echo NASM errors:
    type _nasm_err.txt
    del _nasm_err.txt 2>nul
    pause
    exit /b 1
)
del _nasm_err.txt 2>nul

echo [3/3] Linking...
"%GOLINK%" /entry:%ENTRY% /console "%OBJ%" kernel32.dll /fo "%EXE%" 2>_link_err.txt
if exist "%EXE%" (
    echo. > "%ERRFILE%" 2>nul
    del _link_err.txt 2>nul
    del "%OBJ%" 2>nul
    del "%ASM%" 2>nul
    echo.
    echo ==========================================
    echo   SUCCESS!
    echo   %EXE% created
    for %%a in ("%EXE%") do echo   Size: %%~za bytes
    echo ==========================================
    echo.
    "%EXE%"
    echo.
    pause
    exit /b 0
)

echo [ERROR] GoLink failed
echo GoLink Error: > "%ERRFILE%"
type _link_err.txt >> "%ERRFILE%"
echo. >> "%ERRFILE%"
echo Generated ASM file: >> "%ERRFILE%"
type "%ASM%" >> "%ERRFILE%"
type _link_err.txt
del _link_err.txt 2>nul
pause
exit /b 1